Fix to append rather than overwrite data in existing files
segmentio/analytics-swift pull request #184
Opened 2023-01-24 19:04 UTC by dannys42

The existing code will result in malformed JSON being sent to the server because of partial events overwriting the start of existing files.  This fix will ensure we always append to a pre-existing file.

2023-01-24 22:19 UTC, dmcgloin requested changes

2023-01-24 22:19 UTC, dmcgloin commented on Sources/Segment/Utilities/OutputFileStream.swift
> +            }
Likely could improve with code for all supported platforms

2023-01-25 06:27 UTC, dmcgloin approved these changes

2023-01-26 01:37 UTC, dmcgloin approved these changes

2023-01-26 21:13 UTC, bsneed commented
Thanks @dannys42 @dmcgloin!  I haven't seen this happen before (not saying it's not possible, just that I haven't seen it) in my testing or test suites.  It definitely can't hurt for sure though.  Thanks so much for the PR!

2023-01-26 21:13 UTC, merged

2023-01-28 01:21 UTC, dmcgloin commented
Thanks for merging, @bsneed. Any idea when a release is targeted with this change?

2023-02-03 17:38 UTC, bsneed commented
Just released.  Thanks @dmcgloin !  https://github.com/segmentio/analytics-swift/releases/tag/1.3.5